const SOURCES = [
  'SEC EDGAR',
  'StockTwits',
  'Reddit',
  'Breaking News',
  'Truth Social',
  'X/Twitter',
  'Federal Register',
  'Trading Halts',
  'Economic Calendar',
  'IR Monitor',
  'Newswire',
  'Whitehouse',
  'FTC',
  'FDA',
  'Dilution Monitor',
];

export function About() {
  return (
    <div className="mx-auto max-w-4xl py-8">
      <section className="rounded-3xl border border-border-default bg-[linear-gradient(145deg,rgba(249,115,22,0.1),rgba(17,18,23,0.98))] p-6 shadow-[0_18px_40px_var(--shadow-color)]">
        <h1 className="text-3xl font-semibold text-text-primary">About Event Radar</h1>
        <p className="mt-3 max-w-2xl text-sm leading-6 text-text-secondary">
          Event Radar is a real-time event intelligence product for traders who need to know
          what happened, why it matters, and where the original source came from before the
          market fully reprices the news.
        </p>
      </section>

      <div className="mt-6 grid gap-4">
        <section className="rounded-2xl border border-border-default bg-bg-surface/96 p-6">
          <h2 className="text-xl font-semibold text-text-primary">What is Event Radar?</h2>
          <p className="mt-3 text-sm leading-7 text-text-secondary">
            Event Radar monitors a broad set of market-moving data sources around the clock and
            turns raw filings, headlines, social posts, regulatory actions, and macro releases
            into a single event stream. The goal is to reduce reaction time without hiding the
            underlying evidence.
          </p>
          <p className="mt-3 text-sm leading-7 text-text-secondary">
            Each alert is designed to show the source, the AI interpretation, and the trust
            context side by side. That includes severity, directional framing, historical
            pattern context, and links back to the original record whenever possible.
          </p>
          <p className="mt-3 text-sm leading-7 text-text-secondary">
            The product is built for speed, but not at the expense of honesty. When a metric or
            visualization is still maturing, we show a clear placeholder instead of implying
            precision the data does not support yet.
          </p>
        </section>

        <section className="rounded-2xl border border-border-default bg-bg-surface/96 p-6">
          <h2 className="text-xl font-semibold text-text-primary">Data Sources</h2>
          <ul className="mt-4 grid gap-2 text-sm text-text-secondary sm:grid-cols-2 lg:grid-cols-3">
            {SOURCES.map((source) => (
              <li
                key={source}
                className="rounded-2xl border border-overlay-medium bg-bg-elevated/60 px-4 py-3"
              >
                {source}
              </li>
            ))}
          </ul>
        </section>

        <section className="rounded-2xl border border-border-default bg-bg-surface/96 p-6">
          <h2 className="text-xl font-semibold text-text-primary">How It Works</h2>
          <p className="mt-3 text-sm leading-7 text-text-secondary">
            Sources flow into Event Radar first, where source-specific scanners normalize the
            payloads into a common event format. Those events are then enriched and classified by
            AI so the product can summarize the catalyst, estimate direction, and assign severity.
          </p>
          <p className="mt-3 text-sm leading-7 text-text-secondary">
            A golden judge layer reviews the event context before delivery. Once an alert clears
            that step, it can be routed to the live dashboard, iOS push, Telegram, Discord, or
            other configured channels.
          </p>
          <p className="mt-4 rounded-2xl border border-overlay-medium bg-bg-elevated/60 px-4 py-3 text-sm text-text-primary">
            Sources → AI Classification → Golden Judge → Delivery
          </p>
        </section>

        <section className="rounded-2xl border border-border-default bg-bg-surface/96 p-6">
          <h2 className="text-xl font-semibold text-text-primary">AI Disclosure</h2>
          <p className="mt-3 text-sm leading-7 text-text-secondary">
            Event summaries, bull/bear cases, and severity classifications are generated by AI
            (GPT-4). Always verify with primary sources.
          </p>
        </section>

        <section className="rounded-2xl border border-border-default bg-bg-surface/96 p-6">
          <h2 className="text-xl font-semibold text-text-primary">Contact</h2>
          <p className="mt-3 text-sm leading-7 text-text-secondary">
            Questions? Reach us at [placeholder email]
          </p>
        </section>
      </div>
    </div>
  );
}
