export const COMPANY_TICKER_MAP: Record<string, string> = {
  'apple': 'AAPL',
  'nvidia': 'NVDA',
  'tesla': 'TSLA',
  'microsoft': 'MSFT',
  'amazon': 'AMZN',
  'google': 'GOOGL',
  'alphabet': 'GOOGL',
  'meta': 'META',
  'facebook': 'META',
  'netflix': 'NFLX',
  'boeing': 'BA',
  'disney': 'DIS',
  'jpmorgan': 'JPM',
  'goldman sachs': 'GS',
  'walmart': 'WMT',
  'costco': 'COST',
  'target': 'TGT',
  'home depot': 'HD',
  'coca-cola': 'KO',
  'pepsi': 'PEP',
  'pepsico': 'PEP',
  'intel': 'INTC',
  'amd': 'AMD',
  'qualcomm': 'QCOM',
  'broadcom': 'AVGO',
  'cisco': 'CSCO',
  'oracle': 'ORCL',
  'salesforce': 'CRM',
  'adobe': 'ADBE',
  'paypal': 'PYPL',
  'mastercard': 'MA',
  'visa': 'V',
  'berkshire': 'BRK.B',
  'johnson & johnson': 'JNJ',
  'pfizer': 'PFE',
  'moderna': 'MRNA',
  'unitedhealth': 'UNH',
  'exxon': 'XOM',
  'chevron': 'CVX',
  'shell': 'SHEL',
  'bp': 'BP',
  'palantir': 'PLTR',
  'snowflake': 'SNOW',
  'uber': 'UBER',
  'airbnb': 'ABNB',
  'coinbase': 'COIN',
  'robinhood': 'HOOD',
  'gamestop': 'GME',
  'amc': 'AMC',
  'nio': 'NIO',
  'rivian': 'RIVN',
  'lucid': 'LCID',
  'ford': 'F',
  'general motors': 'GM',
  'lockheed': 'LMT',
  'raytheon': 'RTX',
  'northrop': 'NOC',
  'caterpillar': 'CAT',
  'deere': 'DE',
  '3m': 'MMM',
  'micron': 'MU',
  'applied materials': 'AMAT',
  'lam research': 'LRCX',
  'crowdstrike': 'CRWD',
  'palo alto': 'PANW',
  'datadog': 'DDOG',
  'servicenow': 'NOW',
  'workday': 'WDAY',
  'spotify': 'SPOT',
  'roku': 'ROKU',
  'pinterest': 'PINS',
  'snap': 'SNAP',
  'twitter': 'TWTR',
  'baidu': 'BIDU',
  'alibaba': 'BABA',
  'tencent': 'TCEHY',
  'samsung': 'SSNLF',
  'openai': 'MSFT',
  'chatgpt': 'MSFT',
  'anthropic': 'AMZN',
  'claude': 'AMZN',
};
